In [9]:
import pandas as pd
import os

print("Working directory:", os.getcwd())

file_path = "C:\Users\sharan\OneDrive\Desktop\MGNREGA-Karnataka-Analytics\data"

df = pd.read_excel(file_path)

df.head()

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3628899136.py, line 6)

In [10]:
import os
print("Current Directory:", os.getcwd())
print("Files inside /data folder:", os.listdir("../data"))

Current Directory: C:\Users\sharan

FileNotFoundError: [WinError 3] The system cannot find the path specified: '../data'

In [2]:
import os
print(os.getcwd())

C:\Users\sharan

In [3]:
os.listdir()

['.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'data_analysis.ipynb',
 'Documents',
 'Downloads',
 'Favorites',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{032f02cf-4676-11ef-8287-8c47be171a1b}.TM.blf',
 'NTUSER.DAT{032f02cf-4676-11ef-8287-8c47be171a1b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{032f02cf-4676-11ef-8287-8c47be171a1b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']

In [6]:
import os
print(os.getcwd())
os.listdir()

C:\Users\sharan

['.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'data_analysis.ipynb',
 'Documents',
 'Downloads',
 'Favorites',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{032f02cf-4676-11ef-8287-8c47be171a1b}.TM.blf',
 'NTUSER.DAT{032f02cf-4676-11ef-8287-8c47be171a1b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{032f02cf-4676-11ef-8287-8c47be171a1b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']

In [7]:
import os
print(os.getcwd())
os.listdir()

C:\Users\sharan

['.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.matplotlib',
 'AppData',
 'Application Data',
 'Contacts',
 'Cookies',
 'data_analysis.ipynb',
 'Documents',
 'Downloads',
 'Favorites',
 'Links',
 'Local Settings',
 'Microsoft',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{032f02cf-4676-11ef-8287-8c47be171a1b}.TM.blf',
 'NTUSER.DAT{032f02cf-4676-11ef-8287-8c47be171a1b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{032f02cf-4676-11ef-8287-8c47be171a1b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Templates',
 'Untitled.ipynb',
 'Videos']

In [11]:
import pandas as pd

file_path = r"C:\Users\sharan\OneDrive\Desktop\MGNREGA-Karnataka-Analytics\data\Karnataka_mgnrega_FY2023_24.xlsx"

df = pd.read_excel(file_path)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sharan\\OneDrive\\Desktop\\MGNREGA-Karnataka-Analytics\\data\\Karnataka_mgnrega_FY2023_24.xlsx'

In [12]:
import pandas as pd

file_path = r"C:\Users\sharan\OneDrive\Desktop\MGNREGA-Karnataka-Analytics\data\karnataka_mgnrega_data.xlsx"

df = pd.read_excel(file_path)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sharan\\OneDrive\\Desktop\\MGNREGA-Karnataka-Analytics\\data\\karnataka_mgnrega_data.xlsx'

In [13]:
import os

data_folder = r"C:\Users\sharan\OneDrive\Desktop\MGNREGA-Karnataka-Analytics\data"
print(os.listdir(data_folder))

['Karnataka_mgnrega_FY2023_24.xlsx.xlsx']

In [14]:
import os

data_folder = r"C:\Users\sharan\OneDrive\Desktop\MGNREGA-Karnataka-Analytics\data"
print(os.listdir(data_folder))

['Karnataka_mgnrega_FY2023_24.xlsx']

In [15]:
import pandas as pd

file_path = r"C:\Users\sharan\OneDrive\Desktop\MGNREGA-Karnataka-Analytics\data\Karnataka_mgnrega_FY2023_24.xlsx"

df = pd.read_excel(file_path)
df.head()

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
0,2023-2024,Oct,15,KARNATAKA,1506,BIDAR,3718182,301.960117,36,403,...,243758,458226,59522,11223.398562,1979598,60,29.80,29.82,100.20,NaN
1,2023-2024,Oct,15,KARNATAKA,1512,DAVANAGERE,2445015,303.854850,38,291,...,235323,516597,34141,7425.832724,1247991,80,33.86,28.87,99.95,NaN
2,2023-2024,Oct,15,KARNATAKA,1518,KODAGU,349294,299.625644,34,115,...,87030,189900,9466,1042.796116,180754,79,31.50,17.27,100.31,NaN
3,2023-2024,Oct,15,KARNATAKA,1520,KOPPAL,7829222,286.004306,43,3611,...,320915,843308,60562,22390.393381,4083854,69,18.65,68.46,99.68,NaN
4,2023-2024,Oct,15,KARNATAKA,1530,Yadgir,3492803,295.596929,34,521,...,267551,530503,57636,10321.745205,1810812,81,40.05,43.70,99.91,NaN

In [16]:
xls = pd.ExcelFile(file_path)
xls.sheet_names

['ee03643a-ee4c-48c2-ac30-9f2ff26']

In [17]:
import pandas as pd

file_path = r"C:\Users\sharan\OneDrive\Desktop\MGNREGA-Karnataka-Analytics\data\Karnataka_mgnrega_FY2023_24.xlsx"

df = pd.read_excel(file_path)
df.head()

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
0,2023-2024,Oct,15,KARNATAKA,1506,BIDAR,3718182,301.960117,36,403,...,243758,458226,59522,11223.398562,1979598,60,29.80,29.82,100.20,NaN
1,2023-2024,Oct,15,KARNATAKA,1512,DAVANAGERE,2445015,303.854850,38,291,...,235323,516597,34141,7425.832724,1247991,80,33.86,28.87,99.95,NaN
2,2023-2024,Oct,15,KARNATAKA,1518,KODAGU,349294,299.625644,34,115,...,87030,189900,9466,1042.796116,180754,79,31.50,17.27,100.31,NaN
3,2023-2024,Oct,15,KARNATAKA,1520,KOPPAL,7829222,286.004306,43,3611,...,320915,843308,60562,22390.393381,4083854,69,18.65,68.46,99.68,NaN
4,2023-2024,Oct,15,KARNATAKA,1530,Yadgir,3492803,295.596929,34,521,...,267551,530503,57636,10321.745205,1810812,81,40.05,43.70,99.91,NaN

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 36 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   fin_year                                               372 non-null    object
 1   month                                                  372 non-null    object
 2   state_code                                             372 non-null    int64
 3   state_name                                             372 non-null    object
 4   district_code                                          372 non-null    int64
 5   district_name                                          372 non-null    object
 6   Approved_Labour_Budget                                 372 non-null    int64
 7   Average_Wage_rate_per_day_per_person                   372 non-null    float64
 8   Average_days_of_employment_provided_per_Household      372 non-null    int64
 9   Differently_abled_persons_worked                       372 non-null    int64
 10  Material_and_skilled_Wages                             372 non-null    float64
 11  Number_of_Completed_Works                              372 non-null    int64
 12  Number_of_GPs_with_NIL_exp                             372 non-null    int64
 13  Number_of_Ongoing_Works                                372 non-null    int64
 14  Persondays_of_Central_Liability_so_far                 372 non-null    int64
 15  SC_persondays                                          372 non-null    int64
 16  SC_workers_against_active_workers                      372 non-null    int64
 17  ST_persondays                                          372 non-null    int64
 18  ST_workers_against_active_workers                      372 non-null    int64
 19  Total_Adm_Expenditure                                  372 non-null    float64
 20  Total_Exp                                              372 non-null    float64
 21  Total_Households_Worked                                372 non-null    int64
 22  Total_Individuals_Worked                               372 non-null    int64
 23  Total_No_of_Active_Job_Cards                           372 non-null    int64
 24  Total_No_of_Active_Workers                             372 non-null    int64
 25  Total_No_of_HHs_completed_100_Days_of_Wage_Employment  372 non-null    int64
 26  Total_No_of_JobCards_issued                            372 non-null    int64
 27  Total_No_of_Workers                                    372 non-null    int64
 28  Total_No_of_Works_Takenup                              372 non-null    int64
 29  Wages                                                  372 non-null    float64
 30  Women_Persondays                                       372 non-null    int64
 31  percent_of_Category_B_Works                            372 non-null    int64
 32  percent_of_Expenditure_on_Agriculture_Allied_Works     372 non-null    float64
 33  percent_of_NRM_Expenditure                             372 non-null    float64
 34  percentage_payments_gererated_within_15_days           372 non-null    float64
 35  Remarks                                                0 non-null      float64
dtypes: float64(9), int64(23), object(4)
memory usage: 104.8+ KB

In [20]:
df.columns

Index(['fin_year', 'month', 'state_code', 'state_name', 'district_code',
       'district_name', 'Approved_Labour_Budget',
       'Average_Wage_rate_per_day_per_person',
       'Average_days_of_employment_provided_per_Household',
       'Differently_abled_persons_worked', 'Material_and_skilled_Wages',
       'Number_of_Completed_Works', 'Number_of_GPs_with_NIL_exp',
       'Number_of_Ongoing_Works', 'Persondays_of_Central_Liability_so_far',
       'SC_persondays', 'SC_workers_against_active_workers', 'ST_persondays',
       'ST_workers_against_active_workers', 'Total_Adm_Expenditure',
       'Total_Exp', 'Total_Households_Worked', 'Total_Individuals_Worked',
       'Total_No_of_Active_Job_Cards', 'Total_No_of_Active_Workers',
       'Total_No_of_HHs_completed_100_Days_of_Wage_Employment',
       'Total_No_of_JobCards_issued', 'Total_No_of_Workers',
       'Total_No_of_Works_Takenup', 'Wages', 'Women_Persondays',
       'percent_of_Category_B_Works',
       'percent_of_Expenditure_on_Agriculture_Allied_Works',
       'percent_of_NRM_Expenditure',
       'percentage_payments_gererated_within_15_days', 'Remarks'],
      dtype='object')

In [21]:
df.head()

,fin_year,month,state_code,state_name,district_code,district_name,Approved_Labour_Budget,Average_Wage_rate_per_day_per_person,Average_days_of_employment_provided_per_Household,Differently_abled_persons_worked,...,Total_No_of_JobCards_issued,Total_No_of_Workers,Total_No_of_Works_Takenup,Wages,Women_Persondays,percent_of_Category_B_Works,percent_of_Expenditure_on_Agriculture_Allied_Works,percent_of_NRM_Expenditure,percentage_payments_gererated_within_15_days,Remarks
0,2023-2024,Oct,15,KARNATAKA,1506,BIDAR,3718182,301.960117,36,403,...,243758,458226,59522,11223.398562,1979598,60,29.80,29.82,100.20,NaN
1,2023-2024,Oct,15,KARNATAKA,1512,DAVANAGERE,2445015,303.854850,38,291,...,235323,516597,34141,7425.832724,1247991,80,33.86,28.87,99.95,NaN
2,2023-2024,Oct,15,KARNATAKA,1518,KODAGU,349294,299.625644,34,115,...,87030,189900,9466,1042.796116,180754,79,31.50,17.27,100.31,NaN
3,2023-2024,Oct,15,KARNATAKA,1520,KOPPAL,7829222,286.004306,43,3611,...,320915,843308,60562,22390.393381,4083854,69,18.65,68.46,99.68,NaN
4,2023-2024,Oct,15,KARNATAKA,1530,Yadgir,3492803,295.596929,34,521,...,267551,530503,57636,10321.745205,1810812,81,40.05,43.70,99.91,NaN

In [22]:

df['District'].nunique()

KeyError: 'District'

In [23]:
for col in df.columns:
    print(col)

fin_year
month
state_code
state_name
district_code
district_name
Approved_Labour_Budget
Average_Wage_rate_per_day_per_person
Average_days_of_employment_provided_per_Household
Differently_abled_persons_worked
Material_and_skilled_Wages
Number_of_Completed_Works
Number_of_GPs_with_NIL_exp
Number_of_Ongoing_Works
Persondays_of_Central_Liability_so_far
SC_persondays
SC_workers_against_active_workers
ST_persondays
ST_workers_against_active_workers
Total_Adm_Expenditure
Total_Exp
Total_Households_Worked
Total_Individuals_Worked
Total_No_of_Active_Job_Cards
Total_No_of_Active_Workers
Total_No_of_HHs_completed_100_Days_of_Wage_Employment
Total_No_of_JobCards_issued
Total_No_of_Workers
Total_No_of_Works_Takenup
Wages
Women_Persondays
percent_of_Category_B_Works
percent_of_Expenditure_on_Agriculture_Allied_Works
percent_of_NRM_Expenditure
percentage_payments_gererated_within_15_days
Remarks

In [24]:
df['district_name'].nunique()

31

In [25]:
df['district_name'].unique()

array(['BIDAR', 'DAVANAGERE', 'KODAGU', 'KOPPAL', 'Yadgir', 'KALABURAGI',
       'CHIKKABALLAPURA', 'BALLARI', 'VIJAYPURA', 'DHARWAR', 'KOLAR',
       'CHIKKAMAGALURU', 'HAVERI', 'MANDYA', 'RAICHUR', 'TUMAKURU',
       'BENGALURU', 'BELAGAVI', 'BENGALURU RURAL', 'CHAMARAJA NAGARA',
       'GADAG', 'HASSAN', 'SHIVAMOGGA', 'VIJAYANAGARA', 'UDUPI', 'MYSURU',
       'UTTARA KANNADA', 'RAMANAGARA', 'BAGALKOTE', 'CHITRADURGA',
       'DAKSHINA KANNADA'], dtype=object)

In [26]:
df.isna().sum()

fin_year                                                   0
month                                                      0
state_code                                                 0
state_name                                                 0
district_code                                              0
district_name                                              0
Approved_Labour_Budget                                     0
Average_Wage_rate_per_day_per_person                       0
Average_days_of_employment_provided_per_Household          0
Differently_abled_persons_worked                           0
Material_and_skilled_Wages                                 0
Number_of_Completed_Works                                  0
Number_of_GPs_with_NIL_exp                                 0
Number_of_Ongoing_Works                                    0
Persondays_of_Central_Liability_so_far                     0
SC_persondays                                              0
SC_workers_against_active_workers                          0
ST_persondays                                              0
ST_workers_against_active_workers                          0
Total_Adm_Expenditure                                      0
Total_Exp                                                  0
Total_Households_Worked                                    0
Total_Individuals_Worked                                   0
Total_No_of_Active_Job_Cards                               0
Total_No_of_Active_Workers                                 0
Total_No_of_HHs_completed_100_Days_of_Wage_Employment      0
Total_No_of_JobCards_issued                                0
Total_No_of_Workers                                        0
Total_No_of_Works_Takenup                                  0
Wages                                                      0
Women_Persondays                                           0
percent_of_Category_B_Works                                0
percent_of_Expenditure_on_Agriculture_Allied_Works         0
percent_of_NRM_Expenditure                                 0
percentage_payments_gererated_within_15_days               0
Remarks                                                  372
dtype: int64

In [27]:
# Show column names
print(df.columns)

# Rename columns for easy use
df.rename(columns={
    'district_name': 'District',
    'state_name': 'State'
}, inplace=True)

# Check missing values
df.isnull().sum()

# Remove rows where District is missing
df = df[df['District'].notna()]

# Convert Month to numeric if required
# (Some datasets have month names)
df['month'] = df['month'].astype(str)

print("✅ Data Cleaning Completed")

Index(['fin_year', 'month', 'state_code', 'state_name', 'district_code',
       'district_name', 'Approved_Labour_Budget',
       'Average_Wage_rate_per_day_per_person',
       'Average_days_of_employment_provided_per_Household',
       'Differently_abled_persons_worked', 'Material_and_skilled_Wages',
       'Number_of_Completed_Works', 'Number_of_GPs_with_NIL_exp',
       'Number_of_Ongoing_Works', 'Persondays_of_Central_Liability_so_far',
       'SC_persondays', 'SC_workers_against_active_workers', 'ST_persondays',
       'ST_workers_against_active_workers', 'Total_Adm_Expenditure',
       'Total_Exp', 'Total_Households_Worked', 'Total_Individuals_Worked',
       'Total_No_of_Active_Job_Cards', 'Total_No_of_Active_Workers',
       'Total_No_of_HHs_completed_100_Days_of_Wage_Employment',
       'Total_No_of_JobCards_issued', 'Total_No_of_Workers',
       'Total_No_of_Works_Takenup', 'Wages', 'Women_Persondays',
       'percent_of_Category_B_Works',
       'percent_of_Expenditure_on_Agriculture_Allied_Works',
       'percent_of_NRM_Expenditure',
       'percentage_payments_gererated_within_15_days', 'Remarks'],
      dtype='object')
✅ Data Cleaning Completed